name: Test predict_vad_w2v2.py

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        sudo apt install sox
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python predict_vad_w2v2.py > output.txt
        if grep -q "Arousal, dominance, valence: \[\[0\.32000706 0\.4031646  0\.54803556\]\]" output.txt; then
          echo "Test success!"
        else
          echo "Test failed: output does not match expected value"
          exit 1
        fi
